### ISSUE TITLE
Error on Flutter version 3.29.0

### ISSUE THREAD

**Issue by Dansp** [josorio9111/disk_space_update#1]
I'm getting this error after an upgrade of Flutter from 3.27.3 to 3.29.0. Please update this lib

e: file:///home/daniel/.pub-cache/hosted/pub.dev/disk_space_update-0.0.2/android/src/main/kotlin/com/avangenio/disk_space_update/DiskSpaceUpdatePlugin.kt:14:48 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':disk_space_update:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 49s

**Comment by josorio9111** [comment]
Fixed error

**Comment by Kaddtechnologies** [comment]
What was the fix? I see this also on the base package as well Disk Space Plus
